### ISSUE TITLE
CheckRequirements - Department

### ISSUE THREAD

**Issue by Squibsie** [KDani-99/FivePD-API#25]
It appears that the new CheckRequirements() method can't be used to check a player's department as the object is only created after the call out is received?

It would be good if this object is accessible by CheckRequirements() so that you can specify callouts to certain depts.

**Comment by Squibsie** [comment]
Actually, I think this might be a bug or my poor understanding of the usage.

I have attempted to get playerdata as per the usage instruction on the wiki in the main method of my class. 

```
dynamic playerData = this.GetPlayerData();
            string dept = playerData.Department;
            if (dept == "Los Santos Police Department")
            {
                jobSelect = random.Next(0, 3);
            }
            else if (dept == "San Andreas Sheriffs Department")
            {
                jobSelect = random.Next(4, 7);
            }
            else if (dept == "San Andreas Highway Patrol")
            {
                jobSelect = random.Next(8, 11);
            }
```

I have tried to oversimplify this to troubleshoot, initially i used:

`if (playerdata.Department == "Los Santos Police Department")` etc, but to no avail. I get the error:

```
 MainThrd/ Failed to run a tick for f71xtq2w_wzxӿႁᏴཤѤሁӄ๫ሤරቶၥӍ๊഑ù່းᏡЎᎶޑૉሾÏዄፙ൐ંທኴᏔົᏄ༂ጽ༢ŵኲ: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.

[     75093] [    GTAProcess]             MainThrd/   at SuicidalPersonOnLedgeLS.SuicidalPersonOnBridge..ctor () [0x0016d] in <1b2e1248f5db4327834e25b8d3f6192e>:0 

[     75093] [    GTAProcess]             MainThrd/   at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)

[     75093] [    GTAProcess]             MainThrd/   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[     75093] [    GTAProcess]             MainThrd/    --- End of inner exception stack trace ---

[     75093] [    GTAProcess]             MainThrd/   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00014] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[     75093] [    GTAProcess]             MainThrd/   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000a8] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[     75093] [    GTAProcess]             MainThrd/   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[     75093] [    GTAProcess]             MainThrd/   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[     75093] [    GTAProcess]             MainThrd/   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00020] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[     75093] [    GTAProcess]             MainThrd/   at System.Activator.CreateInstance (System.Type type) [0x00000] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[     75093] [    GTAProcess]             MainThrd/   at f71xtq2w_wzxӿႁᏴཤѤሁӄ๫ሤරቶၥӍ๊഑ù່းᏡЎᎶޑૉሾÏዄፙ൐ંທኴᏔົᏄ༂ጽ༢ŵኴ.f71xtq2w_wzx´࿗ѯॠңіമӫ࿿௨උนဳ஺২э္඲௪ဲӶ൞௑৻෴൑ҦÓ࿏Ň઱Œõĸቚ๕໱༕ણ () [0x00139] in <ea593c91bb304c7c9f6f50dd810ec282>:0 

[     75093] [    GTAProcess]             MainThrd/   at f71xtq2w_wzxӿႁᏴཤѤሁӄ๫ሤරቶၥӍ๊഑ù່းᏡЎᎶޑૉሾÏዄፙ൐ંທኴᏔົᏄ༂ጽ༢ŵኲ+f71xtq2w_wzxӲુுૈઁሕண፩ţൡኣঐ૪ሸ௑ዌӌရᏙጫၩෳूģਭюंѳ੎Ꮯৱቋ௺¢ӕᏎ੖Ĵ࿅.MoveNext () [0x00068] in <ea593c91bb304c7c9f6f50dd810ec282>:0 
[     75093] [    GTAProcess]             MainThrd/ 
```

Which appears to suggest that the instance of the object hasn't yet been created? Do I have to call this method after a certain point? in Init() for instance?

**Comment by KDani-99** [comment]
No, the object should be available. I'll try that.

**Comment by KDani-99** [comment]
Found the issue. It'll be fixed in the next update. 
Thank you!

**Comment by Squibsie** [comment]
Phew, at least it wasn't me going insane!

**Comment by Squibsie** [comment]
@KDani-99 Rather than open a new issue, I am still having the same issue as above. I assume as I am trying to use this incorrectly.
Is there anywhere specific that the method has to be called? I was trying to use it when it selects the location of the callout to detect department and then modify the location dependent on that, but it's still not happy :(

**Comment by KDani-99** [comment]
It should work anywhere. I'll try to reproduce it.
Did you update to 1.0.5.2? (It was not an API update )

**Comment by Squibsie** [comment]
I did, it may just be my poor understanding as I'm not a 'fluent' C# coder.

Could you perhaps do a quick example callout that fetches the playerdata
object and returns the department name or some thing?

At least then I can see if there's a missing link.

**Comment by KDani-99** [comment]
I tried it and it was working,
I'll try it again and screenshot it.

**Comment by KDani-99** [comment]
Feel free to join FivePD API Support discord server, so we can discuss it faster
**[https://discord.gg/zPjDPHg](https://discord.gg/zPjDPHg)**

**Comment by Squibsie** [comment]
I am in there, same username :)

**Comment by KDani-99** [comment]
Workaround:
To get the player's data before you set the location, you can call InitBase in Init, but you must set the same data that you set in the constructor. (so basically twice)
```cs
public async override Task Init()
{
 InitBase(World.GetNextPositionOnStreet(Game.PlayerPed.GetOffsetPosition(new Vector3(offsetX, offsetY, 0))));

            this.ShortName = "Domestic Dispute 2";
            this.CalloutDescription = "Neighbours have reported loud screaming and fighting at the residence! Things are heating up, get there quick!";
            this.ResponseCode = 3;
            this.StartDistance = 30f;
            this.FixedLocation = true;
  ....
}

```
